### PR TITLE
Update defmt

### PR DESCRIPTION
**Pull request by mattico**
Waiting on defmt-decoder 0.2.1 release

### CODE REVIEW

**Comment by burrbull** [comment]
ping

**Comment by Tiwalun** [comment]
We were working on release automation in the main probe-rs repo, which broke the CI here. We will fix this in the main repo, you don't have to change the versions here.

**Comment by Tiwalun** [comment]
bors try

**Review by Tiwalun — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
