### PR TITLE
Add in field that has been added to probe-rs

### PR DESCRIPTION
**Pull request by derekdreery**
I needed this patch to be able to build.

### CODE REVIEW

**Review by Yatekii — APPROVED** [review]
Thanks a lot!

bors r+

**Comment by Yatekii** [comment]
bors retry

**Comment by Tiwalun** [comment]
bors retry

Let's hope that GH Actions work again.

**Comment by Tiwalun** [comment]
@derekdreery Please update the `Cargo.lock` file as well, otherwise CI will still use the older `probe-rs` version without the new field.

**Comment by Yatekii** [comment]
bors retry

**Pull request merged**
