### PR TITLE
add --probe like present in cargo-flash

### PR DESCRIPTION
**Pull request by benmkw**
mostly copied form cargo-flash, cli arg takes precedence over config 

I gathered we wanted to support this and the goal was to unify flash and embed args?

### CODE REVIEW

**Review by Yatekii — APPROVED** [review]
bors r+

**Review by Yatekii — CHANGES_REQUESTED** [review]
@benmkw Could you fix this? :)

**Comment by benmkw** [comment]
was just waiting for this to happen, force pushed :D

**Review by Yatekii — APPROVED** [review]
bors r+

**Pull request merged**
