### PR TITLE
Use 127.0.0.1:1337 for GDB by default as localhost might deafult to IPv6 and lead to problems with GDB connecting

### PR DESCRIPTION
**Pull request by Yatekii**

### CODE REVIEW

**Comment by adamgreig** [comment]
Hmm, I appreciate we just had a really confusing problem for a user because of this, but I don't know if this is the best way to solve it. How come cargo-embed, given 'localhost', binds to v6, while gdb, given 'localhost', attempts to connect to v4? Could cargo-embed listen on both the v4 and the v6 address?

**Comment by Yatekii** [comment]
I agree, this would be a nicer solution :)

**Comment by Yatekii** [comment]
Well apparently Debian is garbage as we are used to it:

> In other words, on some systems, IPV6_V6ONLY will be forced on IPv6 sockets, whether or not IPV6_V6ONLY has been set by the caller (lighttpd). These include the default configurations of modern Debian Linux, FreeBSD, Mac OS X

https://redmine.lighttpd.net/projects/lighttpd/wiki/IPv6-Config

I did not figure yet how to force Rust to listen on both :/

**Comment by Tiwalun** [comment]
GDB supports specifying the connection just with the port, like this: `target remote :1337`. Have you tried if this avoids the IPv6 problems? According to the documentation, GDB should support IPv6 just fine: https://sourceware.org/gdb/onlinedocs/gdb/Connecting.html

**Comment by Yatekii** [comment]
> Have you tried if this avoids the IPv6 problems?

Yap we tried this :) Did not work for them on Debian and also doesn't work for me on Ubuntu :)

**Review by Tiwalun — APPROVED** [review]
Looks good!

bors r+

**Comment by Tiwalun** [comment]
> Hmm, I appreciate we just had a really confusing problem for a user because of this, but I don't know if this is the best way to solve it. How come cargo-embed, given 'localhost', binds to v6, while gdb, given 'localhost', attempts to connect to v4? Could cargo-embed listen on both the v4 and the v6 address?

From what I've found out, the only reliable way to do this would be to open two separate sockets, one listening on IPv4 and one on IPv6. Since this only concerns the default setting, and you always can set it explicitly to use IPv6by suppling an IPv6 address, I think this is a good solution for the issue.

(Up-to-date versions of GDB also shouldn't have this problem, since about two years GDB supports both IPv6 and IPv4).

**Pull request merged**
